import React, { useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import Logo from '../components/Logo';

const Terms = () => {
  const navigate = useNavigate();

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div style={{ backgroundColor: '#030812', color: '#ffffff', minHeight: '100vh', fontFamily: '"DM Sans", sans-serif' }}>
      <style>
        {`
          @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&family=Syne:wght@600;700;800&display=swap');
          
          .legal-container h1, .legal-container h2, .legal-container h3 {
            font-family: 'Syne', sans-serif;
            color: #ffffff;
            margin-top: 3rem;
            margin-bottom: 1.25rem;
          }
          .legal-container h2 { 
            font-size: 1.75rem; 
            border-bottom: 1px solid rgba(255,255,255,0.08); 
            padding-bottom: 0.75rem; 
          }
          .legal-container h3 { font-size: 1.3rem; margin-top: 2rem; color: #e2e8f0; }
          .legal-container p, .legal-container ul {
            font-family: 'DM Sans', sans-serif;
            color: #94a3b8;
            line-height: 1.8;
            font-size: 1.05rem;
            margin-bottom: 1.5rem;
          }
          .legal-container li { 
            margin-bottom: 0.75rem; 
            position: relative;
            padding-left: 1.5rem;
          }
          .legal-container li::before {
            content: "•";
            color: #0062ff;
            position: absolute;
            left: 0;
            font-weight: bold;
          }
          .legal-container a { color: #0062ff; text-decoration: none; font-weight: 500; transition: color 0.2s; }
          .legal-container a:hover { color: #3384ff; text-decoration: underline; }
          .accent { color: #0062ff; }
        `}
      </style>

      {/* Main Content */}
      <main className="legal-container" style={{ maxWidth: '820px', margin: '0 auto', padding: '2rem 2rem 6rem' }}>
        <button 
          onClick={() => navigate(-1)} 
          style={{ 
            background: 'transparent', border: 'none', color: '#94a3b8', 
            padding: '0', cursor: 'pointer', 
            fontFamily: '"DM Sans", sans-serif', fontSize: '1rem',
            display: 'inline-flex', alignItems: 'center', gap: '8px',
            transition: 'color 0.2s',
            marginBottom: '3rem'
          }}
          onMouseOver={(e) => { e.currentTarget.style.color = '#ffffff'; }}
          onMouseOut={(e) => { e.currentTarget.style.color = '#94a3b8'; }}
        >
          <span>←</span> Back
        </button>

        <div style={{ textAlign: 'center', marginBottom: '4rem' }}>
          <span style={{ color: '#0062ff', fontWeight: 700, letterSpacing: '0.15em', fontSize: '0.85rem', textTransform: 'uppercase', marginBottom: '1rem', display: 'block' }}>
            Legal Documentation
          </span>
          <h1 style={{ fontSize: '3.5rem', fontWeight: 800, marginTop: 0, letterSpacing: '-0.03em' }}>
            Terms of Service
          </h1>
          <p style={{ color: 'rgba(255,255,255,0.4)', marginTop: '1rem', fontSize: '1rem' }}>
            Last Updated: April 2026
          </p>
        </div>

        <p>
          Welcome to <strong>IRISAI</strong>. These Terms of Service ("Terms") govern your use of the IRISAI web application, platform, and related services. By accessing or using our services, you agree to be bound by these Terms.
        </p>

        <h2>1. Medical Disclaimer</h2>
        <div style={{ padding: '1.25rem', background: 'rgba(239, 68, 68, 0.1)', border: '1px solid rgba(239, 68, 68, 0.3)', borderRadius: '8px', marginBottom: '1.5rem', marginTop: '1.5rem' }}>
          <p style={{ margin: 0, color: '#fca5a5' }}>
            <strong>Important Notice:</strong> IRISAI provides deep learning-based analyses for preliminary screening purposes only. The information, predictions, and reports generated by our AI models do <strong>not</strong> constitute a medical diagnosis, professional medical advice, or a substitute for consultation with a certified healthcare provider. You must always consult a licensed ophthalmologist for clinical evaluation and treatment.
          </p>
        </div>

        <h2>2. User Eligibility</h2>
        <p>
          You must be at least <strong>18 years of age</strong> to register for an account and use the IRISAI platform. By using the service, you represent and warrant that you meet this age requirement and hold the legal capacity to form a binding contract.
        </p>

        <h2>3. Account Registration & Security</h2>
        <p>To utilize the full capabilities of the IRISAI platform, you must register for an account. You agree to:</p>
        <ul style={{ listStyleType: 'none', padding: 0 }}>
          <li>Provide accurate, current, and complete information during registration.</li>
          <li>Maintain the security and confidentiality of your password and account credentials.</li>
          <li>Accept responsibility for all activities that occur under your account.</li>
          <li>Notify IRISAI immediately of any unauthorized use or security breaches.</li>
        </ul>

        <h2>4. Acceptable Use Rules</h2>
        <p>You agree not to engage in any of the following prohibited activities:</p>
        <ul style={{ listStyleType: 'none', padding: 0 }}>
          <li>Uploading malicious software, viruses, or utilizing the platform to distribute malware.</li>
          <li>Attempting to reverse engineer, decompile, or bypass the security mechanisms of the AI models.</li>
          <li>Uploading illegal, non-medical, or non-consensual images.</li>
          <li>Using the service for large-scale automated scraping or unauthorized API access.</li>
        </ul>

        <h2>5. Intellectual Property Ownership</h2>
        <p>
          <strong>IRISAI Ownership:</strong> The IRISAI platform, its proprietary AI models, software, algorithms, designs, and content are the exclusive intellectual property of IRISAI.
        </p>
        <p>
          <strong>User Ownership:</strong> You retain all ownership rights to the eye scan images and clinical data you upload. By uploading content, you grant IRISAI a limited, secure license strictly to process the image for generating your report and improving our deep learning algorithms in an anonymized manner.
        </p>

        <h2>6. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, IRISAI, its affiliates, developers, and partners shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits, revenues, or medical misjudgments incurred, whether directly or indirectly, resulting from your use of the AI health screening services.
        </p>

        <h2>7. Governing Law</h2>
        <p>
          These Terms and your use of the IRISAI platform shall be governed by and construed in accordance with the laws of India. Any disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts located in <span className="accent">Mumbai, Maharashtra, India</span>.
        </p>

      </main>
    </div>
  );
};

export default Terms;
